[build]
  command = "npm run build"
  publish = "dist"
  # Force cache clear

[env.production]
  VITE_API_URL = "https://freelance-hub-o2m8.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
